### ISSUE TITLE
Respeaker setting not honored

### ISSUE THREAD

**Issue by salleq** [nerdaxic/glados-voice-assistant#17] opened 2022-03-14 13:04 UTC
In glados_respeaker.py:
```python
	if "name 'pixel_ring' is not defined" in str(e):
		print("\nERROR: ReSpeaker is probably not connected?")
		#if(os.getenv('RESPEAKER_CONNECTED')):
		#	exit();
```
If I uncomment the two lines that I have commented above, I get the error "ReSpeaker is probably not connected" even though in settings.env there is:
RESPEAKER_CONNECTED				= False

**Comment by eternalliving** [comment] 2022-03-14 15:11
You just need to put the print after the if statement:
```
     if "name 'pixel_ring' is not defined" in str(e):
	if(os.getenv('RESPEAKER_CONNECTED')):
    	    exit();
        print("\nERROR: ReSpeaker is probably not connected?")
        exit();
```

or better yet:
```
     if "name 'pixel_ring' is not defined" in str(e) and os.getenv('RESPEAKER_CONNECTED'):
        print("\nERROR: ReSpeaker is probably not connected?")
        exit();
```

**Comment by eternalliving** [comment] 2022-03-14 15:38
Reviewing the code again it looks like `respeaker_errors(e)` shouldn't even be getting called if RESPEAKER_CONNECTED = False in your settings.env.... could it be getting called from another file?

**Comment by eternalliving** [comment] 2022-03-14 18:01
`if(os.getenv('RESPEAKER_CONNECTED')):` is returning a string which will always = true. I've updated the file with the following for all the if's but this idea will need to be carried into the other files where the getenv's are treated as booleans.
`if(os.getenv('RESPEAKER_CONNECTED', 'False').lower() in ('true', '1', 't')):`

**Comment by nerdaxic** [comment] 2022-03-21 20:31
Thanks guys, confirmed to be working. Closing this dealio

**Closed by nerdaxic** 2022-03-21 20:31 UTC
